### ISSUE TITLE
Feature Request: Export one Template for better merging stuff local vs productive server thing

### ISSUE THREAD

**Issue by begservice** [BayBreezy/strapi-plugin-email-designer-5#11]
Hello it would be nice if we can build the feature to just export one template and import one Template =)

**Comment by BayBreezy** [comment]
Hey yo! Currently, you can import a single template. If you create/edit a template/design, there is an import button next to the save button. The import takes the json object exported by Unlayer.

I definitely can add a button that downloads a single design's HTML or Design Object.

**Comment by BayBreezy** [comment]
@begservice This was implemented in the last release.

Try it out and let me know how it goes.

**Comment by begservice** [comment]
and now this plugin is better than the v4 version thank you !
