### ISSUE TITLE
Install command mistake 

### ISSUE THREAD

**Issue by sergefy13** [BayBreezy/strapi-plugin-email-designer-5#38]
hey bro! Just tried to install the plugin with `npm i strapi-plugin-email-designer-v5`, as defined in documentation but it is wrong one. `npm i strapi-plugin-email-designer-5`  works

Just to let you know) Thank you for your job.

**Comment by BayBreezy** [comment]
Yes. Thank you 🙏🏽

I will have some time at the end of this month to make some good changes to the library and do the merge with the original `email-designer` repo.
